dev:
  logging:
    outputType: console
    filePath: logs.log #ignored

  database:
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    dbname: books
    sslmode: disable
    populate:
      migrate: true
      init: true
      file: init.sql
